### PR TITLE
Create a dir recursively & make compatible with readr 2.0

### PR DESCRIPTION
**Pull request by boshek**
If the weather app directory didn't exist already, additional levels below weren't being created.

### CODE REVIEW

**Comment by boshek** [comment]
A bit of duct tape required to process the normals data correctly. The new version of readr (just out) has some different defaults. We can revert using this function: https://readr.tidyverse.org/reference/with_edition.html

**Comment by steffilazerte** [comment]
A couple of weird things with the stations update I'll fix and push here.

**Comment by boshek** [comment]
@steffilazerte I think this is ready to merge if you have any time for a review.

**Comment by steffilazerte** [comment]
Thanks I'll take a look soon!

**Comment by steffilazerte** [comment]
Looks good! Thanks @boshek! To be clear, this was just fixing some problems I introduced with the new stations() function and the cache? I like the idea of pre-building the vignettes too. If you have time, please implement! But also feel free to direct me to a reference and I can make that happen too 😁  🙏🏼 Thank you!

**Pull request merged**
